-- CreateTable
CREATE TABLE "leituras_sensor" (
    "id" SERIAL NOT NULL,
    "timestamp" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "umidade_solo" DECIMAL(5,2),
    "valor_adc" INTEGER,
    "sensor_ok" BOOLEAN DEFAULT true,
    "fator_local" DECIMAL(5,3),
    "precipitacao_atual" DECIMAL(8,2),
    "precipitacao_24h" DECIMAL(8,2),
    "precipitacao_7d" DECIMAL(8,2),
    "precipitacao_30d" DECIMAL(8,2),
    "status_api_bndmet" VARCHAR(50),
    "qualidade_dados_bndmet" INTEGER,
    "temperatura" DECIMAL(5,2),
    "umidade_externa" DECIMAL(5,2),
    "pressao_atmosferica" DECIMAL(7,2),
    "velocidade_vento" DECIMAL(5,2),
    "descricao_tempo" VARCHAR(100),
    "precipitacao_previsao_6h" DECIMAL(8,2),
    "precipitacao_previsao_24h" DECIMAL(8,2),
    "tendencia_tempo" VARCHAR(200),
    "risco_integrado" DECIMAL(5,2),
    "indice_risco" INTEGER,
    "nivel_alerta" VARCHAR(20),
    "recomendacao" TEXT,
    "confiabilidade" INTEGER,
    "tendencia_piora" BOOLEAN,
    "previsao_umidade_6h" DECIMAL(5,2),
    "previsao_umidade_24h" DECIMAL(5,2),
    "tempo_ate_critico" DECIMAL(8,2),
    "status_sistema" INTEGER,
    "buzzer_ativo" BOOLEAN,
    "modo_manual" BOOLEAN,
    "wifi_conectado" BOOLEAN,
    "blynk_conectado" BOOLEAN,
    "dados_brutos" JSONB,
    "created_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "leituras_sensor_pkey" PRIMARY KEY ("id")
);
